### PR TITLE
Fix i18n messages to use dgraph instead of vector

### PR DESCRIPTION
**Pull request by paladox**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/mediawiki-dgraph-skin/1)

### CODE REVIEW

**Comment by nischayn22** [comment]
Have you tested this works fine?

**Comment by paladox** [comment]
@nischayn22 hi no I haven't tested but this should work 100% since currently your using the vector name in the i18n and using  dgraph in the other files.

**Comment by nischayn22** [comment]
Would be great if you can just test if this doesn't break anything and the
new messages are working.

**Comment by paladox** [comment]
Oh but your using the vector messages so it is already broken, using these updated messages should fix things.

**Comment by nischayn22** [comment]
It's not broken, it still works with a wrong message at some places. Need
to know if it still works and you aren't missing any commas etc.

**Comment by paladox** [comment]
Oh, nope not missing any commas.

you will probably want https://travis-ci.org/ to test your repo.

**Comment by manishrjain** [comment]
Hey @nischayn22, so what's the resolution on this. If there're no issues, we should merge the PR.

**Comment by nischayn22** [comment]
Well its not tested, so I don't know. If you go through the changes there's
nothing more than text so it should probably be fine.

Regards,
Nischay Nahata

**Comment by manishrjain** [comment]
Might make sense to pull it in -- then test it and fix any issues.

**Comment by danielmai** [comment]
Closing this PR as this repo is now archived as per #6.

**Pull request closed without merging**
